name: Feature request
description: Suggest an improvement or a new integration
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem would this solve?
      description: The use case or pain point, not just the proposed solution.
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: What you'd like Stats Umami to do.
    validations:
      required: false
